const defaultBoards = [
  {
    data: [
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }],
    ]
  },
  {
    data: [
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'diamond' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'marble', direction: 'right' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'diamond' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'diamond' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'floor' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'round' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'marble', direction: 'left' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'marble', direction: 'up' }, { type: 'marble', direction: 'up' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'floor' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'marble', direction: 'down' }, { type: 'marble', direction: 'down' }, { type: 'wall', variant: 'round' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }],
      [{ type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }, { type: 'wall', variant: 'square' }],
    ]
  }
]

export default defaultBoards
