
const types = {
    PLAY_BOARD_WRITE: 'PLAY_BOARD_WRITE',

    EDIT_TOGGLE_OPEN: 'EDIT_TOGGLE_OPEN',
    EDIT_WRITE_BOARD: 'EDIT_WRITE_BOARD',
    EDIT_WRITE_BOARD_NEW: 'EDIT_WRITE_BOARD_NEW',
    EDIT_WRITE_COL: 'EDIT_WRITE_COL',
    EDIT_WRITE_ROW: 'EDIT_WRITE_ROW',
    EDIT_WRITE_ROWS_DIRECT: 'EDIT_WRITE_ROWS_DIRECT',
    EDIT_WRITE_COLS_DIRECT: 'EDIT_WRITE_COLS_DIRECT',
    EDIT_PAINTER_SELECT_CHANGE: 'EDIT_PAINTER_SELECT_CHANGE',
    EDIT_CHANGE_CELL: 'EDIT_CHANGE_CELL',
    EDIT_PAINT_MODE_TOGGLE: 'EDIT_PAINT_MODE_TOGGLE',
    EDIT_PAINTER_MODE_SWITCH: 'EDIT_PAINTER_MODE_SWITCH',
    EDIT_PAINTER_FOCUS_UPDATE: 'EDIT_PAINTER_FOCUS_UPDATE',

    UI_MOUSEDOWN_HIGH: 'UI_MOUSEDOWN_HIGH',
    UI_MOUSEDOWN_LOW: 'UI_MOUSEDOWN_LOW',

    FILES_TOGGLE_OPEN: 'FILES_TOGGLE_OPEN',
}

export default types
