
const types = {
  PLAY_BOARD_WRITE: 'PLAY_BOARD_WRITE',

  EDIT_TOGGLE_OPEN: 'EDIT_TOGGLE_OPEN',
  EDIT_WRITE_BOARD_NEW: 'EDIT_WRITE_BOARD_NEW',
  EDIT_WRITE_COL: 'EDIT_WRITE_COL',
  EDIT_WRITE_ROW: 'EDIT_WRITE_ROW',
}

export default types
